// <auto-generated />
using Learn_ASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learn_ASP.Migrations
{
    [DbContext(typeof(LearnASPContext))]
    [Migration("20250512015338_One to One")]
    partial class OnetoOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Learn_ASP.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SerialNumberID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Keyboard",
                            Price = 200000.0,
                            SerialNumberID = 10
                        });
                });

            modelBuilder.Entity("Learn_ASP.Models.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemID")
                        .IsUnique()
                        .HasFilter("[ItemID] IS NOT NULL");

                    b.ToTable("serialNumbers");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ItemID = 4,
                            Name = "KEY001"
                        });
                });

            modelBuilder.Entity("Learn_ASP.Models.SerialNumber", b =>
                {
                    b.HasOne("Learn_ASP.Models.Item", "Item")
                        .WithOne("SerialNumber")
                        .HasForeignKey("Learn_ASP.Models.SerialNumber", "ItemID");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Learn_ASP.Models.Item", b =>
                {
                    b.Navigation("SerialNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
